"""Repository ports used by application and workflow services."""

from __future__ import annotations

from typing import Any, Dict, List, Protocol

from ..contracts.models import WorkflowInstance


class WorkflowRepository(Protocol):
    def save(self, instance: WorkflowInstance) -> str: ...
    def get(self, workflow_id: str) -> WorkflowInstance | None: ...
    def list(self, product_id: str = "") -> List[WorkflowInstance]: ...
    def append_event(self, event: Dict[str, object]) -> None: ...


class ProductBrainRepository(Protocol):
    def current(self, product_id: str) -> Dict[str, Any]: ...
    def commit_state(self, product_id: str, state: Dict[str, Any], *, change_kind: str) -> Dict[str, Any]: ...


class ArtifactRepository(Protocol):
    def get(self, product_id: str, artifact_id: str) -> Dict[str, Any]: ...
    def list(self, product_id: str, artifact_type: str = "") -> List[Dict[str, Any]]: ...


class MaterialRepository(Protocol):
    def get(self, product_id: str, material_id: str) -> Dict[str, Any]: ...
    def list(self, product_id: str) -> List[Dict[str, Any]]: ...
